# Generated by Django 3.1.1 on 2020-09-15 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipoproceso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('id_tipoproceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipoproceso.tipoproceso')),
            ],
        ),
    ]
