# Generated by Django 3.1.1 on 2020-09-16 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proceso',
            old_name='id_tipoproceso',
            new_name='tipoproceso',
        ),
    ]
