# Generated by Django 3.1.1 on 2020-09-16 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipoproceso', '0001_initial'),
        ('proceso', '0002_auto_20200916_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proceso',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipoproceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='tipoproceso.tipoproceso'),
        ),
    ]
