# Generated by Django 3.1.1 on 2020-09-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_coordinador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_evaluado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_evaluador',
        ),
    ]
