# Generated by Django 3.1.1 on 2020-09-16 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
        ('proceso', '0003_auto_20200916_1534'),
        ('cargo', '0002_auto_20200915_1942'),
        ('usuario', '0002_auto_20200915_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='cargo.cargo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='proceso',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='proceso.proceso'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='rol.rol'),
        ),
    ]
