# Generated by Django 3.1.1 on 2020-09-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20200916_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='respondio',
            field=models.BooleanField(default=False),
        ),
    ]
