# Generated by Django 3.1.1 on 2020-09-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_respondio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['id']},
        ),
    ]
