# Generated by Django 3.1.1 on 2020-09-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20200917_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='evaluado',
            field=models.BooleanField(default=False),
        ),
    ]
