# Generated by Django 3.1.1 on 2020-09-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['id']},
        ),
    ]
