# Generated by Django 3.1.1 on 2020-09-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respuestaencuesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaencuesta',
            name='definitiva',
            field=models.IntegerField(default=0),
        ),
    ]
