# Generated by Django 3.1.1 on 2020-09-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respuestaencuesta', '0002_respuestaencuesta_definitiva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestaencuesta',
            name='definitiva',
        ),
    ]
