# Generated by Django 3.1.1 on 2020-09-17 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('preguntasevaluado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntasevaluado',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
