# Generated by Django 3.1.1 on 2020-09-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_auto_20200915_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['id']},
        ),
    ]
