# Generated by Django 3.1.1 on 2020-09-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respuesta', '0002_auto_20200917_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='seleccion',
            field=models.IntegerField(),
        ),
    ]
