# Generated by Django 3.1.1 on 2020-09-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respuesta', '0003_auto_20200917_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuesta',
            options={'ordering': ['id']},
        ),
    ]
